# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  # Global Application Variables
  vmImageName: 'macOS-10.14'

stages:
- stage: SetupDependencies
  displayName: Setup Dependencies
  jobs:
  - job: SetupDependenciesJob
    displayName: Setup Dependencies Job
    pool:
      vmImage: $(vmImageName)
    steps:
    - bash: |
        echo "Installing Common  Depndencies"
        lsof -h